# name: Release
# on:
#   push:
#     branches:
#       - master


# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run tests
#       run: |
#         source venv/bin/activate
#         python manage.py test


#     # - name: Release
#     #   uses: softprops/action-gh-release@v1
#     #   if: startsWith(github.ref, 'refs/tags/')

    
#     - name: Semantic-release
#       run: |
#         source venv/bin/activate
        
#         semantic-release 

#     - name: Create tag and push
#       if: success()
#       run: |
#         git config --local user.name "GitHub Actions"
    

#     # - name: Create Release
#     #   id: create_release
#     #   uses: actions/create-release@v1
#     #   env:
#     #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
#     #   with:
#     #     tag_name: ${{ github.ref }}
#     #     release_name: Release ${{ github.ref }}
#     #     draft: false
#     #     prerelease: false


name: sematic version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.TOKEN }}